Controllers/AuthorDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthorAuthentication.Data;
using AuthorAuthentication.Models;
using NHibernate.Linq;

namespace AuthorAuthentication.Controllers
{
    public class AuthorDetailController : Controller
    {
        // GET: AuthorDetail
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Detail()
        {
            // Retrieve the Author.Id from session
            var authorId = (Guid?)Session["AuthorId"];

            using (var session = NHibernateHelper.CreateSession())
            {
                var details = session.Query<AuthorDetail>().FirstOrDefault(ad => ad.Author.Id == authorId);
                return View(details);
            }
        }


        public ActionResult Edit(int id)
        {

            using (var session = NHibernateHelper.CreateSession())
            {
                var targetBook = session.Get<AuthorDetail>(id);
                return View(targetBook);
            }

        }


        [HttpPost]
        public ActionResult Edit(AuthorDetail detail)
        {
            var authId = Session["AuthorId"];

            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {
                    var existingAuthorDetail = session.Get<AuthorDetail>(detail.Id);
                    existingAuthorDetail.City = detail.City;
                    existingAuthorDetail.Street = detail.Street;
                    existingAuthorDetail.State = detail.State;
                    existingAuthorDetail.Country = detail.Country;

                    session.Update(existingAuthorDetail);
                    txn.Commit();
                    return RedirectToAction("Detail");
                }

            }

        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var targetBook = session.Get<AuthorDetail>(id);
                return View(targetBook);
            }
        }

        [HttpPost]
        public ActionResult Delete(AuthorDetail detail)
        {
            var authId = Session["AuthorId"];

            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {
                    var existingAuthorDetail = session.Get<AuthorDetail>(detail.Id);
                    existingAuthorDetail.City = null;
                    existingAuthorDetail.Street = null;
                    existingAuthorDetail.State = null;
                    existingAuthorDetail.Country = null;

                    session.Update(existingAuthorDetail);
                    txn.Commit();
                    return RedirectToAction("Detail");
                }

            }
        }
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthorAuthentication.Data;
using AuthorAuthentication.Models;

namespace AuthorAuthentication.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            var authorId = (Guid?)Session["AuthorId"];

            if (authorId == null)
            {
                return RedirectToAction("Login", "Author");
            }

            using (var session = NHibernateHelper.CreateSession())
            {
                var books = session.Query<Book>().Where(b => b.Author.Id == authorId).ToList();
                return View(books);
            }
        }

        public ActionResult Details()
        {
            var authorId = (Guid?)Session["AuthorId"];

            if (authorId == null)
            {
                return RedirectToAction("Login", "Author");
            }

            using (var session = NHibernateHelper.CreateSession())
            {
                var books = session.Query<Book>().Where(b => b.Author.Id == authorId).ToList();
                return View(books);
            }
        }



        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Book book)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var authId = Session["AuthorId"];
                using (var txn = session.BeginTransaction())
                {
                    var author = session.Query<Author>().FirstOrDefault(e => e.Id == (Guid)authId);
                    book.Author = author;
                    session.Save(book);
                    txn.Commit();
                    return RedirectToAction("Index");

                }
            }
        }

        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var targetBook = session.Get<Book>(id);
                return View(targetBook);
            }

        }


        [HttpPost]
        public ActionResult Edit(Book book)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {
                    var existingBook = session.Get<Book>(book.Id);
                    existingBook.Title = book.Title;
                    existingBook.Genre = book.Genre;
                    existingBook.Description = book.Description;
                    session.Update(existingBook);
                    txn.Commit();
                    return RedirectToAction("Index");
                }

            }

        }



        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var authId = Session["AuthorId"];
                var author = session.Query<Author>().FirstOrDefault(a => a.Id == (Guid)authId);

                if (author == null)
                {
                    return HttpNotFound("Author not found");
                }

                var targetBook = author.Books.FirstOrDefault(o => o .Id== id);

                if (targetBook == null)
                {
                    return HttpNotFound("Book not found");
                }

                return View(targetBook);
            }
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteBook(int id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {

                    var targetBook = session.Get<Book>(id);

                    session.Delete(targetBook);

                    txn.Commit();

                    return RedirectToAction("Index");
                }
            }

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-dark bg-dark navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
               
                @Html.ActionLink("AuthorBooks", "Index", "Author", new { area = "" }, new { @class = "navbar-brand" })

                @if (!User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("View Books", "AuthorBooks", "Author", new { area = "" }, new { @class = "navbar-brand" })

                }
                else
                {
                    <span style="color:white;" class = "navbar-brand">Welcome @User.Identity.Name</span>
                    @Html.ActionLink("View Books", "Index", "Book", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Author Detail", "Detail", "AuthorDetail", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("LogOut", "Logout", "Author", new { area = "" }, new { @class = "navbar-brand" })

                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>